### ISSUE TITLE
MariaDB returns string type for JSON field

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#3618]
Related to #3474 and #3491 :

[testJSON](https://github.com/pocoproject/poco/blob/bc8e192c2b98af82d26990bd8f1244c8c06846da/Data/MySQL/testsuite/src/SQLExecutor.cpp#L1491) crash when ran against MariaDB. Expected type is FDT_JSON (19), but it returns FDT_BLOB (13); not enough space is available for the result, causing test to crash:

```
*** Connected to [MySQL] test database.
Server Info: 10.3.34-MariaDB-0+deb10u1
Server Version: 100334
Host Info: 127.0.0.1 via TCP/IP

testJSON: columnType=13 (expected: 19)
=================================================================
==18220==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000005bf1 at pc 0x7fedbdf4731e bp 0x7ffc679eca30 sp 0x7ffc679ec1e0
READ of size 70 at 0x602000005bf1 thread T0
    #0 0x7fedbdf4731d  (/lib/x86_64-linux-gnu/libasan.so.5+0x3f31d)
    #1 0x7fedbcd37f39 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x11df39)
    #2 0x7fedbcd38c9a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long) (/lib/x86_64-linux-gnu/libstdc++.so.6+0x11ec9a)
    #3 0x7fedbdead69d in Poco::Data::MySQL::Extractor::extract(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) src/Extractor.cpp:140
    #4 0x55680516d0a3 in Poco::Data::TypeHandler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::extract(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::SharedPtr<Poco::Data::AbstractExtractor, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::Data::AbstractExtractor> >) /home/alex/poco/Data/include/Poco/Data/TypeHandler.h:132
    #5 0x55680516897b in Poco::Data::Extraction<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::extract(unsigned long) /home/alex/poco/Data/include/Poco/Data/Extraction.h:102
    #6 0x7fedbded78b8 in Poco::Data::MySQL::MySQLStatementImpl::next() src/MySQLStatementImpl.cpp:94
    #7 0x7fedbdb14ba4 in Poco::Data::StatementImpl::executeWithoutLimit() src/StatementImpl.cpp:164
    #8 0x7fedbdb13cf3 in Poco::Data::StatementImpl::execute(bool const&) src/StatementImpl.cpp:88
    #9 0x7fedbdb08b96 in Poco::Data::Statement::execute(bool) src/Statement.cpp:128
    #10 0x55680510c85a in SQLExecutor::json() src/SQLExecutor.cpp:1510
    #11 0x55680506129f in MySQLTest::testJSON() src/MySQLTest.cpp:487
    #12 0x55680509c2a5 in CppUnit::TestCaller<MySQLTest>::runTest() (/home/alex/poco/Data/MySQL/testsuite/bin/Linux/x86_64/testrunnerd+0x772a5)
    #13 0x7fedbd06cbe8 in CppUnit::TestCase::run(CppUnit::TestResult*, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (std::exception const&)> const&) src/TestCase.cpp:116
    #14 0x7fedbd0717fb in CppUnit::TestRunner::run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (std::exception const&)> const&) src/TestRunner.cpp:142
    #15 0x556805057f7d in main src/Driver.cpp:17
    #16 0x7fedbc8de09a in __libc_start_main ../csu/libc-start.c:308
    #17 0x556805054b29 in _start (/home/alex/poco/Data/MySQL/testsuite/bin/Linux/x86_64/testrunnerd+0x2fb29)

0x602000005bf1 is located 0 bytes to the right of 1-byte region [0x602000005bf0,0x602000005bf1)
allocated by thread T0 here:
    #0 0x7fedbdff1518 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9518)
    #1 0x7fedbdedafd0 in Poco::Data::MySQL::ResultMetadata::init(st_mysql_stmt*) src/ResultMetadata.cpp:207
    #2 0x7fedbded7e1b in Poco::Data::MySQL::MySQLStatementImpl::compileImpl() src/MySQLStatementImpl.cpp:126
    #3 0x7fedbdb14d39 in Poco::Data::StatementImpl::compile() src/StatementImpl.cpp:184
    #4 0x7fedbdb13cc7 in Poco::Data::StatementImpl::execute(bool const&) src/StatementImpl.cpp:86
    #5 0x7fedbdb08b96 in Poco::Data::Statement::execute(bool) src/Statement.cpp:128
    #6 0x55680510c85a in SQLExecutor::json() src/SQLExecutor.cpp:1510
    #7 0x55680506129f in MySQLTest::testJSON() src/MySQLTest.cpp:487
    #8 0x55680509c2a5 in CppUnit::TestCaller<MySQLTest>::runTest() (/home/alex/poco/Data/MySQL/testsuite/bin/Linux/x86_64/testrunnerd+0x772a5)
    #9 0x7fedbd06cbe8 in CppUnit::TestCase::run(CppUnit::TestResult*, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (std::exception const&)> const&) src/TestCase.cpp:116
    #10 0x7fedbd0717fb in CppUnit::TestRunner::run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (std::exception const&)> const&) src/TestRunner.cpp:142
    #11 0x556805057f7d in main src/Driver.cpp:17
    #12 0x7fedbc8de09a in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: heap-buffer-overflow (/lib/x86_64-linux-gnu/libasan.so.5+0x3f31d) 
Shadow bytes around the buggy address:
  0x0c047fff8b20: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 04 fa
  0x0c047fff8b30: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c047fff8b40: fa fa 00 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c047fff8b50: fa fa fd fd fa fa 04 fa fa fa 04 fa fa fa 00 fa
  0x0c047fff8b60: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 00 00
=>0x0c047fff8b70: fa fa 00 fa fa fa 00 fa fa fa 01 fa fa fa[01]fa
  0x0c047fff8b80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8bb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==18220==ABORTING
```
https://mariadb.com/kb/en/json-data-type/

This should be addressed before release, or JSON support removed IMO.

@hectots
@hmartinez82 
@obiltschnig

**Comment by hmartinez82** [comment]
Indeed the unit test was only tested against MySQL Server. 
Question: Is the unit test expected to be built using MySQL Server and still run against MariaDB or should I use MariaDB libs to build Poco/Data/MySQL first ?

**Comment by hmartinez82** [comment]
I was able to build Poco/Net/MySQL with MariaDB's include and lib folders and I was able to repro the testJSON() failure. Investigating now

**Comment by hmartinez82** [comment]
MariaDB gladly accepts creating a table of type JSON, but this is the table description after it's created:
```
+-----------+-------------+------+-----+---------+-------+
| Field     | Type        | Null | Key | Default | Extra |
+-----------+-------------+------+-----+---------+-------+
| LastName  | varchar(30) | YES  |     | NULL    |       |
| FirstName | varchar(30) | YES  |     | NULL    |       |
| Address   | varchar(30) | YES  |     | NULL    |       |
| Biography | longtext    | YES  |     | NULL    |       |
+-----------+-------------+------+-----+---------+-------+
```
In MySQL:
```
+-----------+-------------+------+-----+---------+-------+
| Field     | Type        | Null | Key | Default | Extra |
+-----------+-------------+------+-----+---------+-------+
| LastName  | varchar(30) | YES  |     | NULL    |       |
| FirstName | varchar(30) | YES  |     | NULL    |       |
| Address   | varchar(30) | YES  |     | NULL    |       |
| Biography | json        | YES  |     | NULL    |       |
+-----------+-------------+------+-----+---------+-------+
```
Lovely... 🐬1 - 🦭0
